/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reconova_java_FastDetectJni */

#ifndef _Included_com_reconova_java_FastDetectJni
#define _Included_com_reconova_java_FastDetectJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reconova_java_FastDetectJni
 * Method:    initFace
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_reconova_java_FastDetectJni_initFace
  (JNIEnv *, jclass, jstring, jstring,  jobject);

/*
 * Class:     com_reconova_java_FastDetectJni
 * Method:    InitChipset
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_reconova_java_FastDetectJni_InitChipset
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_reconova_java_FastDetectJni
 * Method:    destroyFace
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_reconova_java_FastDetectJni_destroyFace
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_reconova_java_FastDetectJni
 * Method:    getVersion
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_reconova_java_FastDetectJni_getVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_reconova_java_FastDetectJni
 * Method:    SetFaceSize
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_reconova_java_FastDetectJni_SetFaceSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_reconova_java_FastDetectJni
 * Method:    detectFace
 * Signature: (JLcom/reconova/java/model/RecoImage;I)[Lcom/reconova/java/model/RwFaceRect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_reconova_java_FastDetectJni_detectFace
  (JNIEnv *, jclass, jlong, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
